In [2]:
import numpy as np

In [5]:
#determine the length of the matrix
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([10, 11, 12])
print("Length of A:", len(A))
print("Length of B:", len(B))

Length of A: 3
Length of B: 3


In [7]:
# Add B as the fourth row of A to create C
C = np.vstack([A, B])
print("Matrix C:\n", C)

Matrix C:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
# Create D from rows 2, 3, 4 and columns 3, 4 of C
D = C[1:4, 1:3]
print("Matrix D:\n", D)

Matrix D:
 [[ 5  6]
 [ 8  9]
 [11 12]]


In [9]:
#Transpose D to create E
E = D.T
print("Matrix E:\n", E)

Matrix E:
 [[ 5  8 11]
 [ 6  9 12]]


In [10]:
#Check the size of E
print("Size of E:", E.shape)

Size of E: (2, 3)


In [12]:
#Create equally spaced vectors
vector = np.linspace(1, 10, 5)
print("Equally spaced vector:", vector)

Equally spaced vector: [ 1.    3.25  5.5   7.75 10.  ]


In [15]:
#Find the max  in each column and row of A
print("Max in each column:", np.max(A, axis=0))
print("Min in each column:", np.min(A, axis=0))


Max in each column: [7 8 9]
Min in each column: [1 2 3]


In [14]:
##Find the min in each column and row of A
print("Max in each row:", np.max(A, axis=1))
print("Min in each row:", np.min(A, axis=1))

Max in each row: [3 6 9]
Min in each row: [1 4 7]


In [18]:
#Calculate mean and sum in each column and row of A
print("Mean of each column:", np.mean(A, axis=0))
print("Sum of each column:", np.sum(A, axis=0))

print("Mean of each row:", np.mean(A, axis=1))
print("Sum of each row:", np.sum(A, axis=1))

Mean of each column: [4. 5. 6.]
Sum of each column: [12 15 18]
Mean of each row: [2. 5. 8.]
Sum of each row: [ 6 15 24]


In [21]:
#Create random matrices F and G
F = np.random.randint(1, 10, (3, 3))
G = np.random.randint(1, 10, (3, 3))
print("Matrix F:\n", F)
print("Matrix G:\n", G)

Matrix F:
 [[9 1 2]
 [5 8 9]
 [2 1 2]]
Matrix G:
 [[3 1 3]
 [9 5 4]
 [9 6 8]]


In [22]:
#Perform scalar multiplication, addition, subtraction, element-wise multiplication
print("F * 2:\n", F * 2)
print("F + G:\n", F + G)
print("F - G:\n", F - G)
print("Element-wise multiplication:\n", F * G)


F * 2:
 [[18  2  4]
 [10 16 18]
 [ 4  2  4]]
F + G:
 [[12  2  5]
 [14 13 13]
 [11  7 10]]
F - G:
 [[ 6  0 -1]
 [-4  3  5]
 [-7 -5 -6]]
Element-wise multiplication:
 [[27  1  6]
 [45 40 36]
 [18  6 16]]


In [23]:
#Check size of F and A, perform matrix multiplication if compatible
if F.shape[1] == A.shape[0]:
    print("Matrix Multiplication:\n", np.dot(F, A))

Matrix Multiplication:
 [[ 27  39  51]
 [100 122 144]
 [ 20  25  30]]


In [25]:
#Generate special matrices
identity_matrix = np.eye(3)
zero_matrix = np.zeros((5, 3))
one_matrix = np.ones((4, 2))
S = np.diag([1, 2, 7])
random_matrix = np.random.randint(1, 10, (6, 6))
diagonal_elements = np.diag(random_matrix)
sparse_matrix = np.diag([1, 2, 3, 4])
dense_matrix = sparse_matrix.astype(float)

print("Identity Matrix:\n", identity_matrix)
print("Zero Matrix:\n", zero_matrix)
print("One Matrix:\n", one_matrix)
print("Diagonal Matrix S:\n", S)
print("Extracted diagonal elements:\n", diagonal_elements)
print("Sparse diagonal matrix converted to dense:\n", dense_matrix)

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
One Matrix:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Diagonal Matrix S:
 [[1 0 0]
 [0 2 0]
 [0 0 7]]
Extracted diagonal elements:
 [5 1 6 3 2 5]
Sparse diagonal matrix converted to dense:
 [[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 4.]]
