In [2]:
import numpy as np
import scipy.linalg as la
import time

# Define Matrix A and vector b
A = np.array([[3, 2, -1], [2, -2, 4], [-1, 0.5, -1]])
b = np.array([1, -2, 0])

In [3]:
# Solve the system Ax = b using numpy's solve function
x = np.linalg.solve(A, b)
# Print the solution vector X
print("\nSolution vector x:")
print(x)


Solution vector x:
[ 1. -2. -2.]


In [4]:
# Calculate the residual r = A*x - b
r = np.dot(A, x) - b
# Print the residual vector r
print("\nResidual vector r:")
print(r)


Residual vector r:
[ 4.44089210e-16  1.77635684e-15 -2.22044605e-16]


In [6]:
P, L, U = la.lu(A)
y = np.linalg.solve(L, np.dot(P, b))
x_lu = np.linalg.solve(U, y)
print("Solution using LU Decomposition:", x_lu)

Solution using LU Decomposition: [ 1. -2. -2.]


In [9]:
# Solve the system Ax = b using numpy's least squares function 
y = np.linalg.lstsq(A, b, rcond=None) [0]
# Print the solution vector y
print("\nSolution vector y:")
print(y)


Solution vector y:
[ 1. -2. -2.]


In [7]:
# Solve the system Ax = b using matrix inverse
A_inv = np.linalg.inv(A)
x2= np.dot(A_inv, b)
# Calculate the residual r2 and error err2
r2= np.dot(A, x2) - b
err2 = x - x2
# Print solution vector x2, residual r2 and error err2
print("\nSolution vector x2 using inverse:")
print(x2)
print("\nResidual vector r2:")
print(r2)
print("\nError vector err2:")
print(err2)


Solution vector x2 using inverse:
[ 1. -2. -2.]

Residual vector r2:
[-1.11022302e-16  1.77635684e-15  0.00000000e+00]

Error vector err2:
[ 2.22044605e-16 -2.22044605e-16 -2.22044605e-16]


In [13]:
import numpy as np

def rref(A):
    '''
    Computes the reduced row echelon form (RREF) of a matrix A.
    Parameters:
    A: numpy.ndarray
    Input matrix of shape (m, n)
    Returns:
    R: numpy.ndarray
    Reduced row echelon form of matrix A
    '''
    A = A.astype(float)
    m, n = A.shape
    lead = 0
    
    for r in range(m):
        if lead >= n:
            break
        if A[r, lead] == 0:  # Find a row with a non-zero element in the current column
            for i in range(r + 1, m):
                if A[i, lead] != 0:
                    A[[r, i]] = A[[i, r]]  # Swap rows
                    break
        if A[r, lead] != 0:  # If the lead element is non-zero, normalize the row
            A[r] = A[r] / A[r, lead]
        for i in range(m):  # Eliminate all other entries in the column
            if i != r and A[i, lead] != 0:
                A[i] = A[i] - A[i, lead] * A[r]
        lead += 1
    return A

# Example setup
A = np.array([[1, 2, -1], [2, 4, -1], [-1, 1, 3]], dtype=float)
b = np.array([3, 6, 4], dtype=float)
x = np.array([1, 2, 3], dtype=float)  # This is the known solution (for error calculation)

# Compute augmented matrix [A|b]
C = np.hstack((A, b.reshape(-1, 1)))
print("Augmented matrix [A|b]:")
print(C)

# Compute the reduced row echelon form of the augmented matrix
R = rref(C)
print("\nReduced Row Echelon Form (RREF) of [A|b]:")
print(R)

# Extract the solution vector from the last column of the RREF matrix
x3 = R[:, -1]
print("\nSolution vector x3 (from RREF):")
print(x3)

# Calculate residuals r3 = np.dot(A, x3) - b
r3 = np.dot(A, x3) - b
print("\nResidual vector r3 (from RREF):")
print(r3)

# Calculate the error vector err3 = x - x3
err3 = x - x3
print("\nError vector err3 (difference between x and x3):")
print(err3)


Augmented matrix [A|b]:
[[ 1.  2. -1.  3.]
 [ 2.  4. -1.  6.]
 [-1.  1.  3.  4.]]

Reduced Row Echelon Form (RREF) of [A|b]:
[[ 1.          0.          0.         -1.66666667]
 [ 0.          1.          0.          2.33333333]
 [ 0.          0.          1.          0.        ]]

Solution vector x3 (from RREF):
[-1.66666667  2.33333333  0.        ]

Residual vector r3 (from RREF):
[0. 0. 0.]

Error vector err3 (difference between x and x3):
[ 2.66666667 -0.33333333  3.        ]


In [14]:
import numpy as np
import time

# Define your matrix A and vector b
A = np.array([[1, 2, -1], [2, 4, -1], [-1, 1, 3]], dtype=float)
b = np.array([3, 6, 4], dtype=float)

# Method 1: Solve using solve operator
start_time = time.time()
x1 = np.linalg.solve(A, b)
end_time = time.time()
time_backslash = end_time - start_time  # Fix the time calculation

# Method 2: Solve using matrix inverse
start_time = time.time()
x2 = np.linalg.inv(A) @ b
end_time = time.time()
time_inv = end_time - start_time  # Fix the time calculation

# Method 3: Solve using reduced row echelon form (rref)
start_time = time.time()
C = np.hstack((A, b.reshape(-1, 1)))  # Ensure b is a column vector
R = rref(C)
x3 = R[:, -1]
end_time = time.time()
time_rref = end_time - start_time  # Fix the time calculation

# Print the solution vectors and computational times
print("\nSolution vector x1 (using backslash operator):")
print(x1)

print("\nSolution vector x2 (using matrix inverse):")
print(x2)

print("\nSolution vector x3 (using reduced row echelon form):")
print(x3)

print("\nComputational times:")
print(f"Backslash operator: {time_backslash:.6f} seconds")
print(f"Matrix inverse: {time_inv:.6f} seconds")
print(f"Reduced row echelon form (rref): {time_rref:.6f} seconds")



Solution vector x1 (using backslash operator):
[-1.66666667  2.33333333 -0.        ]

Solution vector x2 (using matrix inverse):
[-1.66666667  2.33333333  0.        ]

Solution vector x3 (using reduced row echelon form):
[-1.66666667  2.33333333  0.        ]

Computational times:
Backslash operator: 0.000000 seconds
Matrix inverse: 0.003414 seconds
Reduced row echelon form (rref): 0.000000 seconds


In [15]:
import numpy as np

# Define matrix A and vector b for the underdetermined system
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # Fixed the matrix A (no misplaced bracket)
b = np.array([1, 3, 5]).reshape(-1, 1)  # `b` should be a column vector (reshaping)

# Solve the system Ax = b using the least squares solution (backslash operator equivalent)
x, _, _, _ = np.linalg.lstsq(A, b, rcond=None)  # lstsq returns a tuple, so we take the first element

# Calculate the residual r1 = Ax - b
r1 = np.dot(A, x) - b

# Print the solution vector x
print("\nSolution vector x (using lstsq):")
print(x)

# Print the residual vector r1
print("\nResidual vector r1:")
print(r1)

# Obtain another particular solution using the pseudoinverse pinv(A)
A_pinv = np.linalg.pinv(A)
y = np.dot(A_pinv, b)

# Calculate the residual r2 = A * y - b
r2 = np.dot(A, y) - b

# Print the solution vector y from pseudoinverse
print("\nSolution vector y (from pseudoinverse):")
print(y)

# Print the residual vector r2
print("\nResidual vector r2:")
print(r2)



Solution vector x (using lstsq):
[[0.38888889]
 [0.22222222]
 [0.05555556]]

Residual vector r1:
[[1.11022302e-15]
 [2.22044605e-15]
 [2.66453526e-15]]

Solution vector y (from pseudoinverse):
[[0.38888889]
 [0.22222222]
 [0.05555556]]

Residual vector r2:
[[ 6.66133815e-16]
 [ 0.00000000e+00]
 [-8.88178420e-16]]
